[general]
# Use your custom dotfiles location for logs/state if desired
default-save-path = /home/mselimyavuz/Downloads

[ui]
# Indexing based on your 32GB RAM will be instant
index-format = %D %-20.20n %s
timestamp-format = 2006-01-02 15:04
sidebar-width = 25
empty-message = (No messages)

[compose]
# Leveraging your existing Neovim and spellcheck setup
editor = nvim "+set ft=mail" "+set spell" "+set tw=72"
header-layout = To,Cc,Bcc,Subject
# edit-headers = true

[filters]
text/calendar = calendar
text/plain = colorize
text/html = w3m -T text/html -dump | colorize

[templates]
quoted-reply = quoted_reply
new-message = new_message
